[project]
name = "email_automation_sc"
version = "1.0.2"
description = "Un paquete para el envio de correos electronicos automatizados"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
authors = [
  { name = "David Jiménez Cooper", email = "david.jimenez.cooper@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
    "python-dotenv>=0.20.0",
]

[project.urls]
Homepage = "https://github.com/SpiderCoop/Email_Automation"
Repository = "https://github.com/SpiderCoop/Email_Automation"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["email_automation"]

[dependency-groups]
dev = [
    "pytest>=7.0.1",
    "ruff>=0.0.17",
]
